name: 'PocketnetCore build action'
description: 'Build PocketnetCore installers & binaries with selected branch or tag'
branding:
  icon: layers
  color: orange
inputs:
  platform:
    description: 'Destination platform (win, unix, macos)'
    required: true
    default: 'unix'
  branch:
    description: 'Specific branch for building'
    required: true
    default: 'main'
  depsBase:
    description: 'Base branch for use dependencies'
    required: true
    default: '0.21'
  tag:
    description: 'Specific tag for building'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PLATFORM: ${{ inputs.platform }}
    BRANCH: ${{ inputs.branch }}
    DEPSBASE: ${{ inputs.depsBase }}
    TAG: ${{ inputs.tag }}